name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install LaTeX and Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

    - name: Generate PDF
      run: |
        pandoc -s --template=cv.tex cv.yaml -o cv.pdf

    - name: Generate HTML
      run: |
        pandoc -s --template=template.html cv.yaml -o index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
