name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
      - name: Build PDF and HTML
        run: |
          pandoc --template my-template3.tex --pdf-engine=xelatex -o my-cv.pdf my-cv.yml
          pandoc --template my-template.html -o my-cv.html my-cv.yml
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: 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
          publish_dir: ./
